######################## default configuration ####################
baseURL = "https://gloriouscakery.ie"
languageCode = "en"
title = "Glorious build to order cakes in Limerick"
theme = "farina"
summaryLength = "20"
paginate = 10
disqusShortname = ""

[languages]
  [languages.en]
  LangCode = "en"
  [languages.en.params]
    home = "Home"

#    contentDir = "content/english"
    weight = 20
############################## navigation ###############################

      [[languages.en.menu.main]]
      name = "Products"
      URL = "products"
      weight = 1

      [[languages.en.menu.main]]
      name = "Contact"
      URL = "contact"
      weight = 4
  [languages.ru]
  LangCode = "ru"

    [languages.ru.params]
    location = "Лимерик, Ирландия"
    home = "Главная"
#    contentDir = "content/ru"
    weight = 10
    [[languages.ru.menu.main]]
    name = "Ассортимент"
    URL = "products"
    weight = 1

    [[languages.ru.menu.main]]
    name = "Декор"
    URL = "decorations"
    weight = 2

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"



  ############# footer menu #############
  [[menu.footer]]
  name = "Products"
  URL = "products"
  weight = 1

  [[menu.footer]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "FAQ"
  URL = "faq"
  weight = 3

  [[menu.footer]]
  name = "Terms & Conditions"
  URL = "terms-conditions"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 5


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# Contact Information
# mobile = "0124857985320"
email = "kseniia@gloriouscakery.ie"
location = "Limerick, Ireland"
# copyright
copyright = "| Copyright &copy; 2021 [GloriousCakery.ie](https://GloriousCakery.ie) All Rights Reserved |"
# Snipcart Credentials
snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
currencySymbol = "€"

  # Preloader
  [params.preloader]
  enable = false
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = false
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  title = "Facebook"
  icon = "ti-facebook"
  link = "https://www.facebook.com/kspaltseva"

#  [[params.social]]
#  icon = "ti-twitter-alt"
#  link = "#"

#  [[params.social]]
#  icon = "ti-youtube"
#  link = "#"

  [[params.social]]
  title = "Instagran"
  icon = "ti-instagram"
  link = "https://www.instagram.com/kspaltseva/"

#  [[params.social]]
#  icon = "ti-pinterest"
#  link = "#"

  # Contact Form
  [params.contact]
  formAction = "#" # contact form works with formspree.io
